CREATE TABLE dns_policy_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_name VARCHAR(253) NOT NULL,
    match_type VARCHAR(32) NOT NULL,
    action VARCHAR(16) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_dns_policy_rules_domain_match
        UNIQUE (domain_name, match_type),
    CONSTRAINT ck_dns_policy_rules_match_type
        CHECK (match_type IN ('EXACT', 'DOMAIN_AND_SUBDOMAINS')),
    CONSTRAINT ck_dns_policy_rules_action
        CHECK (action IN ('BLOCK'))
);

CREATE INDEX idx_dns_policy_rules_enabled
    ON dns_policy_rules (enabled);
