CREATE TABLE admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_admin_users_username UNIQUE (username)
);

CREATE TABLE admin_user_roles (
    user_id BIGINT NOT NULL,
    role VARCHAR(32) NOT NULL,
    PRIMARY KEY (user_id, role),
    CONSTRAINT fk_admin_user_roles_user
        FOREIGN KEY (user_id) REFERENCES admin_users (id),
    CONSTRAINT ck_admin_user_roles_role
        CHECK (role IN ('VIEWER', 'POLICY_EDITOR', 'ADMIN'))
);

CREATE TABLE admin_api_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    token_label VARCHAR(100) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE,
    revoked_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_used_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_admin_api_tokens_hash UNIQUE (token_hash),
    CONSTRAINT fk_admin_api_tokens_user
        FOREIGN KEY (user_id) REFERENCES admin_users (id)
);

CREATE INDEX idx_admin_api_tokens_user
    ON admin_api_tokens (user_id);
